# -*- coding: utf-8 -*-
"""trabalho.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/riulermendes/MBA-Distributed-Data-Processing/blob/main/trabalho.ipynb
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import col

spark = SparkSession.builder.appName("Trabalho").getOrCreate()

import requests

csv_url = 'https://raw.githubusercontent.com/riulermendes/MBA-Distributed-Data-Processing/refs/heads/main/results_8ABDR.csv'
local_file_path = '/tmp/results_8ABDR.csv'

# Download the file
response = requests.get(csv_url)
with open(local_file_path, 'wb') as f:
    f.write(response.content)

# Read the local file with Spark
bf1 = spark.read.option("header", True) \
                .option("inferSchema", True) \
                .csv(local_file_path)

bf1.printSchema()
bf1.show(n=5)

bf = (
    bf1
    .withColumnRenamed('date','data')
    .withColumnRenamed('home_teamName','Mandante')
    .withColumnRenamed('away_teamName','Vistante')
    .withColumnRenamed('home_scoreHome','Placar_Mandante')
    .withColumnRenamed('away_scoreAway','Placar_Visitante')
    .withColumnRenamed('tournamentName','Torneio')
    .withColumnRenamed('cityCity','Cidade')
    .withColumnRenamed('countryCountry','País')
    .withColumnRenamed('neutralTRUE','NEUTRO')
)

#1 - Quantos registros existem na base?
total_records = bf.count()
print(f"Número total de registros: {total_records}")

#2 - Quantas equipes únicas mandantes existem na base?
distinct_home_teams_count = bf.select(col("Mandante")).distinct().count()
print(f"Número de equipes mandantes únicas: {distinct_home_teams_count}")

#3 - Quantas vezes as equipes mandantes saíram vitoriosas?

home_team_victories = bf.filter(
    col("Placar_Mandante") > col("Placar_Visitante")
).count()

print(f"Número de vezes que as equipes mandantes saíram vitoriosas: {home_team_victories}")

#4 - Quantas vezes as equipes visitantes saíram vitoriosas?
visitor_team_victories =bf.filter(
    col("Placar_Visitante") > col("Placar_Mandante")
).count()

print(f"Número de vezes que as equipes visitantes saíram vitoriosas: {visitor_team_victories}")

#5 - Quantas partidas resultaram em empate?
draw =bf.filter(
    col("Placar_Mandante") == col("Placar_Visitante")
).count()

print(f"Número de vezes que as equipes visitantes saíram vitoriosas: {draw}")

#6 - Quantas partidas foram realizadas em cada país?
bf.groupBy("País").count().orderBy(col("count").desc()).show()

#7 - Qual país teve mais partidas?
bf.groupBy("País").count().orderBy(col("count").desc()).limit(1).show()

#8 - Qual a partida com maior número de gols?
bf.withColumn("total_goals", col("Placar_Mandante") + col("Placar_Visitante")) \
  .orderBy(col("total_goals").desc()) \
  .select("data", "Mandante", "Vistante", "Placar_Mandante", "Placar_Visitante", "total_goals") \
  .limit(1).show()

#9 - Qual a maior goleada?
bf.withColumn("diff", col("Placar_Mandante") - col("Placar_Visitante")) \
  .orderBy(col("diff").desc()) \
  .select("data", "Mandante", "Vistante", "Placar_Mandante", "Placar_Visitante", "diff") \
  .limit(1).show()

#10 - Quantos jogos ocorreram no Brasil?
bf.filter(col("País") == "Brazil").count()